### ISSUE TITLE
Plex External Player Error getting metadata

### ISSUE THREAD

**Issue by Adrian-Rasmussen** [Kayomani/PlexExternalPlayer#6] opened 2016-05-02 12:43 UTC
This is probably a problem on my end, but I'm not sure how to fix it.

Clicking on "Play Externally" or "Open containing folder" results in the following message:
Plex External Player
Error getting metadata fromhttp://127.0.0.1:32400/library/metadata/1056?checkFiles=1&includeExtras=1

Plex Media Server 2.6.1
Plex External Player 1.7 in Tampermonkey with Google Chrome
File are local, on the D: drive

**Comment by sann-nord** [comment] 2016-05-27 00:29
I encountered the same problem.  Found an interim  'workaround' solution - go to https://forums.plex.tv/discussion/219382/plex-media-server-integration-w-videolan-vlc-media-player.

**Comment by Kayomani** [comment] 2016-06-01 20:10
The problem is the line 

  var serverNode = JSON.parse(localStorage.users).users[1].servers[0];

If you change it to 0 and 0 it'll likely work for you.  I need to add some code to check which of credential to use.

**Comment by Kayomani** [comment] 2016-06-01 20:53
Pushed an update to make it try all available tokens, let me know if it works for you now.

**Comment by smarshallsay** [comment] 2016-06-06 19:37
Your update didn't work for me but i made a quick hack of the code and this does, note you'll need to change this code as it is messy and doesn't support multiple servers but I didn't have long :) - 

```

var makeRequest = function(url, user, server){
    return new Promise( function (resolve, reject) {
        var origAccessToken = localStorage.myPlexAccessToken;
        var serverNode = JSON.parse(localStorage.users);
        var tokenToTry = origAccessToken;

        var onError =  function()
            {
               if(user===undefined)
               {
                   user = 0;
                   server = 0;
               } else
               {
                   user++;
                   if(serverNode.users[user] === undefined)
                   {
                       showToast('Could not find authentication info', 1);
                       reject();
                       return;
                   }
                  // server++;
                  // if(serverNode.users[user].servers.length===server)
                  // {
                  //   user++;
                  //   server = 0;
                  // }
               }
               makeRequest(url,user,server).then(resolve, reject);
            };

        if(serverNode===undefined)
        {
            serverNode = {
                users : []
            };
        }

        if(user!==undefined && server !==undefined)
        {
            if(user < serverNode.users.length)
            {
                if(server < serverNode.users[user].servers.length)
                {
                     tokenToTry = serverNode.users[user].servers[server].accessToken;
                }
                else
                {
                    onError();
                    // showToast('Could not find authentication info', 1);
                    // reject();
                    // return;
                }
            }
            else
            {
                showToast('Could not find authentication info', 1);
                reject();
                 return;
            }
        }
        else
        {
            onError();
        }


        GM_xmlhttpRequest({
            method: "GET",
            headers: {
                "X-Plex-Token": tokenToTry
            },
            url: url,
            onload: resolve,
            onreadystatechange: function(state) {
                if (state.readyState === 4) {
                    if(state.status === 401)
                    {
                     onError();
                    } else if (state.status !== 200) {
                        showToast('Error calling: ' + url + '. Response: ' + state.responseText + ' Code:' + state.status + ' Message: ' + state.statusText, 1);
                    }
                }
            },
            onerror: onError
        });
    });
};

```

**Comment by Kayomani** [comment] 2017-03-15 16:59
This should be fixed in the latest version.

**Closed as completed by Kayomani** 2017-03-15 16:59 UTC
